name: gossip_event_sourcing
description: Event Sourcing and CQRS library for Dart applications using the Gossip protocol. Provides core components for building scalable event-driven architectures.
version: 1.0.2
homepage: https://github.com/da1nerd/gossip-mono
repository: https://github.com/da1nerd/gossip-mono
issue_tracker: https://github.com/da1nerd/gossip-mono/issues
documentation: https://github.com/da1nerd/gossip-mono/tree/main/packages/gossip_event_sourcing

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  gossip: ^1.0.2

dev_dependencies:
  test: ^1.25.0
  lints: ^4.0.0

topics:
  - event-sourcing
  - cqrs
  - distributed-systems
  - gossip-protocol
  - command-query
