name: gossip_crdts
description: CRDT (Conflict-free Replicated Data Types) extensions for the gossip protocol library with support for distributed data structures
version: 1.0.3
homepage: https://github.com/da1nerd/gossip-mono
repository: https://github.com/da1nerd/gossip-mono
issue_tracker: https://github.com/da1nerd/gossip-mono/issues
documentation: https://github.com/da1nerd/gossip-mono/tree/main/packages/gossip_crdts

environment:
  sdk: ">=3.9.0 <4.0.0"

resolution: workspace

dependencies:
  gossip: ^1.0.5
  meta: ^1.12.0

dev_dependencies:
  test: ^1.25.0
  lints: ^4.0.0

topics:
  - distributed-systems
  - gossip-protocol
  - conflict-resolution
  - peer-to-peer
  - eventual-consistency
