name: gossip_typed_events
description: Type-safe event extensions for the Dart gossip protocol library with compile-time validation and serialization
version: 1.0.4
homepage: https://github.com/da1nerd/gossip-mono
repository: https://github.com/da1nerd/gossip-mono
issue_tracker: https://github.com/da1nerd/gossip-mono/issues
documentation: https://github.com/da1nerd/gossip-mono/tree/main/packages/gossip_typed_events

environment:
  sdk: ">=3.9.0 <4.0.0"

resolution: workspace

dependencies:
  async: ^2.13.0
  gossip: ^2.0.0
  meta: ^1.12.0

dev_dependencies:
  test: ^1.25.0
  lints: ^4.0.0

topics:
  - distributed-systems
  - gossip-protocol
  - event-synchronization
  - type-safety
