name: gossip
description: A Dart library for implementing gossip-based distributed event synchronization with vector clocks, anti-entropy, and peer-to-peer messaging
version: 1.0.1
homepage: https://github.com/da1nerd/gossip-mono
repository: https://github.com/da1nerd/gossip-mono
issue_tracker: https://github.com/da1nerd/gossip-mono/issues
documentation: https://github.com/da1nerd/gossip-mono/tree/main/packages/gossip

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.12.0

dev_dependencies:
  test: ^1.25.0
  lints: ^4.0.0

topics:
  - distributed-systems
  - gossip-protocol
  - event-synchronization
  - distributed-computing
  - peer-to-peer
  - vector-clocks
  - eventual-consistency
