name: gossip
description: A Dart library for implementing gossip-based distributed event synchronization with vector clocks, anti-entropy, and peer-to-peer messaging
version: 2.1.3
homepage: https://github.com/da1nerd/gossip-mono
repository: https://github.com/da1nerd/gossip-mono
issue_tracker: https://github.com/da1nerd/gossip-mono/issues
documentation: https://github.com/da1nerd/gossip-mono/tree/main/packages/gossip

environment:
  sdk: ">=3.9.0 <4.0.0"

resolution: workspace

dependencies:
  meta: ^1.12.0
  async: ^2.13.0
  uuid: ^4.3.3

dev_dependencies:
  test: ^1.25.0
  lints: ^4.0.0

topics:
  - distributed-systems
  - gossip-protocol
  - event-synchronization
  - peer-to-peer
  - eventual-consistency
