name: Publish Packages to pub.dev

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      packages-changed: ${{ steps.changes.outputs.packages }}
      changed-packages: ${{ steps.list-changes.outputs.packages }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for package changes
        id: changes
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q "^packages/"; then
            echo "packages=true" >> $GITHUB_OUTPUT
          else
            echo "packages=false" >> $GITHUB_OUTPUT
          fi

      - name: List changed packages
        id: list-changes
        if: steps.changes.outputs.packages == 'true'
        run: |
          changed_files=$(git diff --name-only HEAD~1 HEAD | grep "^packages/" | cut -d'/' -f1-2 | sort -u)
          echo "Changed packages: $changed_files"
          echo "packages=$changed_files" >> $GITHUB_OUTPUT

  publish:
    needs: check-changes
    if: needs.check-changes.outputs.packages-changed == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable
          channel: stable

      - name: Install Melos
        run: dart pub global activate melos

      - name: Bootstrap project
        run: melos bootstrap

      - name: Run pre-publish checks
        run: melos run pre-publish-check

      - name: Setup pub credentials
        run: |
          mkdir -p ~/.pub-cache
          echo '${{ secrets.PUB_CREDENTIALS }}' > ~/.pub-cache/credentials.json

      - name: Publish packages
        run: melos run publish-packages

      - name: Create release summary
        run: |
          echo "## 📦 Published Packages" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The following packages were published to pub.dev:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          melos list --no-private --parsable | while read package_path; do
            package_name=$(basename "$package_path")
            version=$(cd "$package_path" && dart pub deps --json | jq -r '.packages[] | select(.name == "'$package_name'") | .version')
            echo "- ✅ **$package_name** v$version" >> $GITHUB_STEP_SUMMARY
          done

      - name: Comment on PR (if applicable)
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Packages have been published to pub.dev! Check the [Actions tab](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.'
            });
